[package]
name = "barcode-parser"
version = "0.1.0"
authors = ["Prayog <ppaudel93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bardecoder = "0.2.2"
image = "0.22.5"
